- name: restart httpd
  service: name=httpd state=restarted enabled=yes
  become: yes

- name: restart the firewalld service
  service: name=firewalld state=restarted

- name: get httpd version
  shell: httpd -v | grep version
  register: httpd_version
  changed_when: false

- name: get httpd built
  shell: httpd -v | grep built
  register: httpd_built
  changed_when: false

- name: save httpd details
  copy: 
    content: >
      {
        "version": "{{ httpd_version.stdout }}",
        "built": "{{ httpd_built.stdout }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/httpd.fact
  become: yes

