- name: gathering facts about vim
  shell: vim --version | grep compiled
  register: vim_version
  changed_when: false

- name: save vim details
  copy: 
    content: >
      {
        "vim_details": "{{ vim_version.stdout }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/vim.fact
  become: yes

