- name: installing system updates
  yum:
    name: vim
    state: present

  notify:
    - gathering facts about vim
    - save vim details

- name: Ensure Facts Directory Exists
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory
  become: yes

